service: server
image: charlie022/lennartmw_website
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
port: 3000

servers:
  web:
    hosts:
      - 49.13.6.131
    labels:
      traefik.http.routers.example_app.rule: Host(`lennartminkweber.com`) || Host(`www.lennartminkweber.com`)
      traefik.http.routers.example_app_secure.entrypoints: websecure
      traefik.http.routers.example_app_secure.rule: Host(`lennartminkweber.com`) || Host(`www.lennartminkweber.com`)
      traefik.http.routers.example_app_secure.tls: true
      traefik.http.routers.example_app_secure.tls.certresolver: letsencrypt

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "p-ungerer@gmx.net"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
